# Generated by Django 4.2.16 on 2024-11-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('fecha_seminario', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profesion', models.CharField(max_length=100)),
                ('institucion_perteneciente', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
